### ISSUE TITLE
Custom Site doesn't wrok

### ISSUE THREAD

**Issue by YellowJack8** [zukas97/NGU#3]
**Describe the bug**
The custom Site tab doesn't do anything

**To Reproduce**
1. Go to 'Custom Site'
2. Put in 'literally any URL'
3. Click on 'Set URL'
4. Nothing Happens
5. See error

**Expected behavior**
I expect the site to actually show up when I click the button.

**Desktop (please complete the following information):**
 - ChromOS
 - Chrome
 - 130.0.6723.126

**Comment by zukas97** [comment]
Thanks for telling me, Its fixed now.
